# This is a basic workflow to help you get started with Actions

name: Comunicador de la Legión

on:
   workflow_dispatch:
    inputs:
      villano:
        description: "¿Qué villano envia el mensaje?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Brainiac
          - Joker
          - Darkseid

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
